In [40]:
import pandas as pd

In [48]:
df = pd.read_csv("class_imbalance/dataset_865_analcatdata_neavote.csv")
df

   Party  Favorable binaryClass
0      R          1           N
1      R          1           N
2      R          2           N
3      R          2           N
4      R          2           P
..   ...        ...         ...
95     D         10           N
96     D         10           N
97     D         10           N
98     R          1           N
99     R          1           N

[100 rows x 3 columns]

In [49]:
split_idx = 80

df.head()

  Party  Favorable binaryClass
0     R          1           N
1     R          1           N
2     R          2           N
3     R          2           N
4     R          2           P

In [50]:
y = df["binaryClass"].map({"P": 1, "N": 0}).astype(float)

X = df.drop(columns=["binaryClass"])
X = pd.get_dummies(X, columns=["Party"], dtype=float)
X["Favorable"] = X["Favorable"] / 10.0

X_train = X.head(80).values.astype(float)
X_test = X.tail(20).values.astype(float)

y_train = y.head(80).values.astype(float)
y_test = y.tail(20).values.astype(float)

In [51]:
from logistic_regression import gradient_descent, prediction
weight, bias = gradient_descent(X_train, y_train)

print(weight, bias)

[-0.79152359 -0.7070176  -0.03630479 -0.45092185] -1.1942442457120597

In [ ]:
log_odds = prediction(weight, bias, X_test)

array([0.06340042, 0.06340042, 0.15131575, 0.14142909, 0.15131575,
       0.14142909, 0.14142909, 0.14142909, 0.06340042, 0.13208786,
       0.13208786, 0.06826616, 0.13208786, 0.06826616, 0.07347603,
       0.06340042, 0.06340042, 0.06340042, 0.15131575, 0.15131575])

In [ ]:
threshold = 0.5