This notebook is meant to fix ~20 datasets

In [2]:
import pandas as pd

## 1

In [3]:
#1 
df = pd.read_csv("../class_imbalance/dataset_1039_hiva_agnostic.csv")
df = df.rename(columns={"label": "target"})
df["target"] = (df["target"] == 1).astype(int)
display(df)
print(df['target'].value_counts())

,attr0,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9,...,attr1608,attr1609,attr1610,attr1611,attr1612,attr1613,attr1614,attr1615,attr1616,target
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4224,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4225,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4226,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4227,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4228,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

target
0    4080
1     149
Name: count, dtype: int64

# 2

In [16]:
#2
df = pd.read_csv("../class_imbalance/dataset_312_scene.csv")
df

,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9,attr10,...,attr291,attr292,attr293,attr294,Beach,Sunset,FallFoliage,Field,Mountain,Urban
0,0.646467,0.666435,0.685047,0.699053,0.652746,0.407864,0.150309,0.535193,0.555689,0.580782,...,0.157332,0.247298,0.014025,0.029709,1,0,0,0,1,0
1,0.770156,0.767255,0.761053,0.745630,0.742231,0.688086,0.708416,0.757351,0.760633,0.740314,...,0.251454,0.137833,0.082672,0.036320,1,0,0,0,0,1
2,0.793984,0.772096,0.761820,0.762213,0.740569,0.734361,0.722677,0.849128,0.839607,0.812746,...,0.017166,0.051125,0.112506,0.083924,1,0,0,0,0,0
3,0.938563,0.949260,0.955621,0.966743,0.968649,0.869619,0.696925,0.953460,0.959631,0.966320,...,0.019267,0.031290,0.049780,0.090959,1,0,0,0,0,0
4,0.512130,0.524684,0.520020,0.504467,0.471209,0.417654,0.364292,0.562266,0.588592,0.584449,...,0.198151,0.238796,0.164270,0.184290,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2402,0.875782,0.901653,0.926227,0.721366,0.795826,0.867642,0.794125,0.899067,0.908963,0.895336,...,0.215147,0.279607,0.254413,0.134350,0,0,0,0,0,1
2403,0.657706,0.669877,0.692338,0.713920,0.727374,0.750354,0.684372,0.718770,0.719916,0.730645,...,0.217201,0.199491,0.048747,0.041638,0,0,0,0,0,1
2404,0.952281,0.944987,0.905556,0.836604,0.875916,0.957034,0.953938,0.967956,0.819636,0.707311,...,0.028002,0.031900,0.017547,0.019734,0,0,0,0,0,1
2405,0.883990,0.899004,0.901019,0.904298,0.846402,0.858145,0.851362,0.852472,0.876665,0.908187,...,0.239041,0.256158,0.226332,0.223070,0,0,0,0,0,1
2406,0.974915,0.866425,0.818144,0.936140,0.938583,0.935087,0.930597,1.000000,0.806074,0.717955,...,0.073742,0.005131,0.025059,0.004033,0,0,0,0,0,1

In [17]:

df.isna().sum().sum()

np.int64(0)

In [13]:

print(df['FallFoliage'].value_counts())

FallFoliage
0    2010
1     397
Name: count, dtype: int64

In [18]:
df = df.rename(columns={"FallFoliage": "target"})

In [19]:
df["target"] = (df["target"] == 1).astype(int)
display(df)

,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9,attr10,...,attr291,attr292,attr293,attr294,Beach,Sunset,target,Field,Mountain,Urban
0,0.646467,0.666435,0.685047,0.699053,0.652746,0.407864,0.150309,0.535193,0.555689,0.580782,...,0.157332,0.247298,0.014025,0.029709,1,0,0,0,1,0
1,0.770156,0.767255,0.761053,0.745630,0.742231,0.688086,0.708416,0.757351,0.760633,0.740314,...,0.251454,0.137833,0.082672,0.036320,1,0,0,0,0,1
2,0.793984,0.772096,0.761820,0.762213,0.740569,0.734361,0.722677,0.849128,0.839607,0.812746,...,0.017166,0.051125,0.112506,0.083924,1,0,0,0,0,0
3,0.938563,0.949260,0.955621,0.966743,0.968649,0.869619,0.696925,0.953460,0.959631,0.966320,...,0.019267,0.031290,0.049780,0.090959,1,0,0,0,0,0
4,0.512130,0.524684,0.520020,0.504467,0.471209,0.417654,0.364292,0.562266,0.588592,0.584449,...,0.198151,0.238796,0.164270,0.184290,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2402,0.875782,0.901653,0.926227,0.721366,0.795826,0.867642,0.794125,0.899067,0.908963,0.895336,...,0.215147,0.279607,0.254413,0.134350,0,0,0,0,0,1
2403,0.657706,0.669877,0.692338,0.713920,0.727374,0.750354,0.684372,0.718770,0.719916,0.730645,...,0.217201,0.199491,0.048747,0.041638,0,0,0,0,0,1
2404,0.952281,0.944987,0.905556,0.836604,0.875916,0.957034,0.953938,0.967956,0.819636,0.707311,...,0.028002,0.031900,0.017547,0.019734,0,0,0,0,0,1
2405,0.883990,0.899004,0.901019,0.904298,0.846402,0.858145,0.851362,0.852472,0.876665,0.908187,...,0.239041,0.256158,0.226332,0.223070,0,0,0,0,0,1
2406,0.974915,0.866425,0.818144,0.936140,0.938583,0.935087,0.930597,1.000000,0.806074,0.717955,...,0.073742,0.005131,0.025059,0.004033,0,0,0,0,0,1

# 3

In [39]:
df = pd.read_csv("../class_imbalance/dataset_316_yeast_ml8.csv")
df

,attr1,attr2,attr3,attr4,attr5,attr6,attr7,attr8,attr9,attr10,...,class5,class6,class7,class8,class9,class10,class11,class12,class13,class14
0,0.004168,-0.170975,-0.156748,-0.142151,0.058781,0.026851,0.197719,0.041850,0.066938,-0.056617,...,0,0,1,1,0,0,0,1,1,0
1,-0.103956,0.011879,-0.098986,-0.054501,-0.007970,0.049113,-0.030580,-0.077933,-0.080529,-0.016267,...,0,0,0,0,0,0,0,0,0,0
2,0.509949,0.401709,0.293799,0.087714,0.011686,-0.006411,-0.006255,0.013646,-0.040666,-0.024447,...,0,0,0,0,0,0,0,1,1,0
3,0.119092,0.004412,-0.002262,0.072254,0.044512,-0.051467,0.074686,-0.007670,0.079438,0.062184,...,0,0,0,0,0,0,0,0,0,0
4,0.042037,0.007054,-0.069483,0.081015,-0.048207,0.089446,-0.004947,0.064456,-0.133387,0.068878,...,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2412,-0.119784,0.001259,-0.123645,-0.015513,-0.059683,0.091032,-0.043302,0.229219,-0.071498,0.182709,...,0,0,0,0,0,0,0,0,0,0
2413,0.085327,0.058590,0.085268,-0.020897,0.068972,0.030125,0.078056,0.011346,0.052618,0.066093,...,0,0,0,0,0,0,0,1,1,0
2414,0.082526,-0.095571,-0.022019,-0.046793,-0.038360,0.041084,0.056509,0.011749,-0.029657,-0.012198,...,0,1,1,1,0,0,0,1,1,0
2415,-0.130830,0.008868,-0.009457,-0.058930,-0.041224,0.042269,0.117717,0.037388,-0.085563,0.136649,...,0,0,0,0,0,0,0,1,1,0
2416,-0.171578,-0.066536,0.168206,0.246831,0.079555,0.016528,-0.088908,-0.212926,-0.280230,-0.187064,...,0,0,0,0,0,0,0,1,1,0

In [40]:

df.isna().sum().sum()

np.int64(0)

In [41]:
df["class14"].value_counts()

class14
0    2383
1      34
Name: count, dtype: int64

In [44]:
df = df.rename(columns={"class14": "target"})
df["target"] = (df["target"] == 0).astype(int)
df["target"].value_counts()

target
0    2383
1      34
Name: count, dtype: int64

# 4

In [53]:
df = pd.read_csv("../class_imbalance/dataset_978_mfeat-factors.csv")
df

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att208,att209,att210,att211,att212,att213,att214,att215,att216,binaryClass
0,98.0,236.0,531.0,673.0,607.0,647.0,2,9,3,6,...,536.0,628.0,632.0,18,36,8,15,12,13,P
1,121.0,193.0,607.0,611.0,585.0,665.0,7,9,2,4,...,458.0,570.0,634.0,15,32,11,13,15,11,P
2,115.0,141.0,590.0,605.0,557.0,627.0,12,6,3,3,...,498.0,572.0,656.0,20,35,16,14,13,6,P
3,90.0,122.0,627.0,692.0,607.0,642.0,0,6,4,5,...,549.0,628.0,621.0,16,35,7,12,15,9,P
4,157.0,167.0,681.0,666.0,587.0,666.0,8,6,1,4,...,525.0,568.0,653.0,16,35,10,15,13,13,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,304.0,242.0,927.0,626.0,564.0,674.0,25,17,0,7,...,507.0,577.0,757.0,15,24,11,14,10,18,N
1996,324.0,330.0,919.0,713.0,609.0,693.0,28,16,8,9,...,554.0,620.0,632.0,12,25,11,10,12,17,N
1997,337.0,299.0,852.0,724.0,581.0,660.0,22,14,10,10,...,579.0,590.0,681.0,18,27,13,15,17,21,N
1998,247.0,261.0,866.0,633.0,565.0,615.0,24,15,2,4,...,498.0,556.0,706.0,16,26,13,13,15,15,N
1999,355.0,379.0,867.0,826.0,638.0,738.0,27,20,16,5,...,665.0,651.0,685.0,13,21,19,12,12,20,N

In [54]:

df.isna().sum().sum()

np.int64(0)

In [55]:
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns,
    index=X.index
)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att208,att209,att210,att211,att212,att213,att214,att215,att216,binaryClass
0,-1.907359,-0.792743,-1.740279,-0.745228,-0.683874,-0.440549,-1.537618,-1.275246,-1.390997,-0.747908,...,-0.895902,-0.233589,-0.669620,0.044701,1.806438,-1.633866,1.175585,-0.858695,-0.097605,P
1,-1.655311,-1.185799,-1.197835,-1.313272,-1.133515,-0.228927,-1.097040,-1.275246,-1.503546,-1.237697,...,-1.553965,-1.258840,-0.645438,-0.528386,1.305206,-1.123920,0.400133,0.652649,-0.529009,P
2,-1.721063,-1.661122,-1.319171,-1.368244,-1.705786,-0.675683,-0.656462,-1.683411,-1.390997,-1.482591,...,-1.216497,-1.223487,-0.379432,0.426758,1.681130,-0.274011,0.787859,-0.354914,-1.607519,P
3,-1.995027,-1.834798,-1.055086,-0.571150,-0.683874,-0.499332,-1.713849,-1.683411,-1.278448,-0.992802,...,-0.786225,-0.233589,-0.802623,-0.337357,1.681130,-1.803848,0.012407,0.652649,-0.960413,P
4,-1.260802,-1.423461,-0.669665,-0.809362,-1.092639,-0.217171,-1.008924,-1.683411,-1.616096,-1.237697,...,-0.988706,-1.294194,-0.415706,-0.337357,1.681130,-1.293902,1.175585,-0.354914,-0.097605,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.350110,-0.737898,1.086141,-1.175842,-1.562718,-0.123117,0.489042,-0.186804,-1.728645,-0.503013,...,-1.140567,-1.135103,0.841774,-0.528386,0.302744,-1.123920,0.787859,-1.866258,0.980905,N
1996,0.569282,0.066495,1.029042,-0.378748,-0.642997,0.100261,0.753389,-0.322859,-0.828250,-0.013224,...,-0.744042,-0.375003,-0.669620,-1.101472,0.428052,-1.123920,-0.763044,-0.858695,0.765203,N
1997,0.711744,-0.216871,0.550834,-0.277966,-1.215268,-0.287711,0.224695,-0.594969,-0.603152,0.231670,...,-0.533124,-0.905306,-0.077154,0.044701,0.678667,-0.783956,1.175585,1.660211,1.628010,N
1998,-0.274529,-0.564222,0.650758,-1.111708,-1.542280,-0.816764,0.400926,-0.458914,-1.503546,-1.237697,...,-1.216497,-1.506315,0.225125,-0.337357,0.553359,-0.783956,0.400133,0.652649,0.333799,N
1999,0.908998,0.514396,0.657896,0.656558,-0.050288,0.629315,0.665273,0.221362,0.072144,-0.992802,...,0.192433,0.172976,-0.028789,-0.910444,-0.073180,0.235935,0.012407,-0.858695,1.412309,N

In [56]:
df = df.rename(columns={"binaryClass": "target"})
df["target"] = (df["target"] == "P").astype(int)
df['target'].value_counts()

target
0    1800
1     200
Name: count, dtype: int64

# 5

In [58]:
df = pd.read_csv("../class_imbalance/dataset_1056_mc1.csv")
df

,LOC_BLANK,BRANCH_COUNT,CALL_PAIRS,LOC_CODE_AND_COMMENT,LOC_COMMENTS,CONDITION_COUNT,CYCLOMATIC_COMPLEXITY,CYCLOMATIC_DENSITY,DECISION_COUNT,DESIGN_COMPLEXITY,...,NODE_COUNT,NORMALIZED_CYLOMATIC_COMPLEXITY,NUM_OPERANDS,NUM_OPERATORS,NUM_UNIQUE_OPERANDS,NUM_UNIQUE_OPERATORS,NUMBER_OF_LINES,PERCENT_COMMENTS,LOC_TOTAL,c
0,0,1.0,0,0,0,0.0,1,1.00,0.0,1,...,2.0,0.50,2.0,3.0,2,3,2.0,0.00,0.0,False
1,0,1.0,0,0,0,0.0,1,1.00,0.0,1,...,2.0,1.00,2.0,3.0,2,3,1.0,0.00,0.0,False
2,0,1.0,1,0,0,0.0,1,1.00,0.0,1,...,3.0,0.50,3.0,6.0,3,6,2.0,0.00,0.0,False
3,8,17.0,11,32,3,12.0,13,0.16,6.0,10,...,32.0,0.14,75.0,137.0,37,25,93.0,42.17,80.0,False
4,4,7.0,1,1,8,12.0,4,0.17,6.0,1,...,18.0,0.11,52.0,61.0,13,10,38.0,28.13,24.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9461,0,1.0,0,0,0,0.0,1,0.33,0.0,1,...,2.0,0.20,3.0,6.0,3,6,5.0,0.00,3.0,False
9462,0,5.0,1,0,0,0.0,3,0.43,0.0,2,...,6.0,0.33,9.0,13.0,6,9,9.0,0.00,7.0,False
9463,1,5.0,3,0,0,8.0,3,0.23,4.0,3,...,14.0,0.19,12.0,19.0,8,10,16.0,0.00,13.0,False
9464,2,1.0,0,0,3,0.0,1,0.14,0.0,1,...,6.0,0.07,11.0,18.0,7,7,14.0,30.00,7.0,False
9465,0,1.0,0,0,0,0.0,1,0.10,0.0,1,...,2.0,0.07,24.0,33.0,12,11,15.0,0.00,10.0,False

In [64]:

df.isna().sum().sum()

np.int64(0)

In [60]:
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=["c"])
y = df["c"].astype(int)

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns,
    index=X.index
)

df_scaled = X_scaled.copy()
df_scaled["c"] = y
df_scaled

,LOC_BLANK,BRANCH_COUNT,CALL_PAIRS,LOC_CODE_AND_COMMENT,LOC_COMMENTS,CONDITION_COUNT,CYCLOMATIC_COMPLEXITY,CYCLOMATIC_DENSITY,DECISION_COUNT,DESIGN_COMPLEXITY,...,NODE_COUNT,NORMALIZED_CYLOMATIC_COMPLEXITY,NUM_OPERANDS,NUM_OPERATORS,NUM_UNIQUE_OPERANDS,NUM_UNIQUE_OPERATORS,NUMBER_OF_LINES,PERCENT_COMMENTS,LOC_TOTAL,c
0,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,0.904709,-0.252267,-0.175472,...,-0.292230,-0.092511,-0.245004,-0.269159,-0.387204,-0.610703,-0.367370,-0.454644,-0.375137,0
1,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,0.904709,-0.252267,-0.175472,...,-0.292230,1.092997,-0.245004,-0.269159,-0.387204,-0.610703,-0.403302,-0.454644,-0.375137,0
2,-0.340104,-0.251702,-0.110853,-0.214872,-0.222243,-0.257285,-0.231175,0.904709,-0.252267,-0.175472,...,-0.230163,-0.092511,-0.224206,-0.223751,-0.288617,-0.064784,-0.367370,-0.454644,-0.375137,0
3,1.407566,1.809266,3.749826,8.552295,0.191176,0.673998,2.770614,-1.399411,0.711007,2.507436,...,1.569769,-0.946077,1.273236,1.759054,3.063349,3.392698,2.902530,1.965410,3.891472,0
4,0.533731,0.521161,-0.110853,0.059102,0.880207,0.673998,0.519272,-1.371981,0.711007,-0.175472,...,0.700836,-1.017207,0.794886,0.608724,0.697255,0.663107,0.926217,1.159682,0.904846,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9461,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,-0.933101,-0.252267,-0.175472,...,-0.292230,-0.803816,-0.224206,-0.223751,-0.288617,-0.064784,-0.259571,-0.454644,-0.215139,0
9462,-0.340104,0.263540,-0.110853,-0.214872,-0.222243,-0.257285,0.269123,-0.658801,-0.252267,0.122629,...,-0.043963,-0.495584,-0.099419,-0.117800,0.007145,0.481134,-0.115839,-0.454644,-0.001809,0
9463,-0.121645,0.263540,0.661283,-0.214872,-0.222243,0.363570,0.269123,-1.207401,0.389916,0.420730,...,0.452570,-0.827526,-0.037026,-0.026984,0.204319,0.663107,0.135692,-0.454644,0.318187,0
9464,0.096813,-0.251702,-0.496921,-0.214872,0.191176,-0.257285,-0.231175,-1.454271,-0.252267,-0.175472,...,-0.043963,-1.112048,-0.057823,-0.042120,0.105732,0.117188,0.063826,1.266997,-0.001809,0
9465,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,-1.563991,-0.252267,-0.175472,...,-0.292230,-1.112048,0.212548,0.184918,0.598668,0.845079,0.099759,-0.454644,0.158189,0

In [63]:
df_scaled = df_scaled.rename(columns={"c": "target"})
df_scaled["target"] = (df_scaled["target"]).astype(int)
df_scaled['target'].value_counts()
df_scaled

,LOC_BLANK,BRANCH_COUNT,CALL_PAIRS,LOC_CODE_AND_COMMENT,LOC_COMMENTS,CONDITION_COUNT,CYCLOMATIC_COMPLEXITY,CYCLOMATIC_DENSITY,DECISION_COUNT,DESIGN_COMPLEXITY,...,NODE_COUNT,NORMALIZED_CYLOMATIC_COMPLEXITY,NUM_OPERANDS,NUM_OPERATORS,NUM_UNIQUE_OPERANDS,NUM_UNIQUE_OPERATORS,NUMBER_OF_LINES,PERCENT_COMMENTS,LOC_TOTAL,target
0,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,0.904709,-0.252267,-0.175472,...,-0.292230,-0.092511,-0.245004,-0.269159,-0.387204,-0.610703,-0.367370,-0.454644,-0.375137,0
1,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,0.904709,-0.252267,-0.175472,...,-0.292230,1.092997,-0.245004,-0.269159,-0.387204,-0.610703,-0.403302,-0.454644,-0.375137,0
2,-0.340104,-0.251702,-0.110853,-0.214872,-0.222243,-0.257285,-0.231175,0.904709,-0.252267,-0.175472,...,-0.230163,-0.092511,-0.224206,-0.223751,-0.288617,-0.064784,-0.367370,-0.454644,-0.375137,0
3,1.407566,1.809266,3.749826,8.552295,0.191176,0.673998,2.770614,-1.399411,0.711007,2.507436,...,1.569769,-0.946077,1.273236,1.759054,3.063349,3.392698,2.902530,1.965410,3.891472,0
4,0.533731,0.521161,-0.110853,0.059102,0.880207,0.673998,0.519272,-1.371981,0.711007,-0.175472,...,0.700836,-1.017207,0.794886,0.608724,0.697255,0.663107,0.926217,1.159682,0.904846,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9461,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,-0.933101,-0.252267,-0.175472,...,-0.292230,-0.803816,-0.224206,-0.223751,-0.288617,-0.064784,-0.259571,-0.454644,-0.215139,0
9462,-0.340104,0.263540,-0.110853,-0.214872,-0.222243,-0.257285,0.269123,-0.658801,-0.252267,0.122629,...,-0.043963,-0.495584,-0.099419,-0.117800,0.007145,0.481134,-0.115839,-0.454644,-0.001809,0
9463,-0.121645,0.263540,0.661283,-0.214872,-0.222243,0.363570,0.269123,-1.207401,0.389916,0.420730,...,0.452570,-0.827526,-0.037026,-0.026984,0.204319,0.663107,0.135692,-0.454644,0.318187,0
9464,0.096813,-0.251702,-0.496921,-0.214872,0.191176,-0.257285,-0.231175,-1.454271,-0.252267,-0.175472,...,-0.043963,-1.112048,-0.057823,-0.042120,0.105732,0.117188,0.063826,1.266997,-0.001809,0
9465,-0.340104,-0.251702,-0.496921,-0.214872,-0.222243,-0.257285,-0.231175,-1.563991,-0.252267,-0.175472,...,-0.292230,-1.112048,0.212548,0.184918,0.598668,0.845079,0.099759,-0.454644,0.158189,0

# 6

In [65]:
df = pd.read_csv("../class_imbalance/dataset_976_JapaneseVowels.csv")
df

,utterance,frame,coefficient1,coefficient2,coefficient3,coefficient4,coefficient5,coefficient6,coefficient7,coefficient8,coefficient9,coefficient10,coefficient11,coefficient12,binaryClass
0,1,1,1.860936,-0.207383,0.261557,-0.214562,-0.171253,-0.118167,-0.277557,0.025668,0.126701,-0.306756,-0.213076,0.088728,N
1,1,2,1.891651,-0.193249,0.235363,-0.249118,-0.112890,-0.112238,-0.311997,-0.027122,0.171457,-0.289431,-0.247722,0.093011,N
2,1,3,1.939205,-0.239664,0.258561,-0.291458,-0.041053,-0.102034,-0.383300,0.019013,0.169510,-0.314894,-0.227908,0.074638,N
3,1,4,1.717517,-0.218572,0.217119,-0.228186,-0.018608,-0.137624,-0.403318,-0.009643,0.164607,-0.323267,-0.210105,0.098098,N
4,1,5,1.741191,-0.279891,0.196583,-0.236377,-0.032012,-0.090612,-0.363134,-0.012571,0.124298,-0.351171,-0.216545,0.113899,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9956,29,7,1.216506,-0.424432,-0.034349,-0.294238,0.166270,-0.397758,0.091827,0.023178,-0.191598,-0.111245,-0.011547,0.425088,N
9957,29,8,1.214579,-0.399925,-0.127891,-0.239583,0.221423,-0.374714,0.046216,0.051754,-0.197824,-0.099159,-0.018177,0.359986,N
9958,29,9,1.170031,-0.306025,-0.145534,-0.195854,0.276371,-0.346794,0.042325,0.031668,-0.181205,-0.077962,-0.024079,0.305890,N
9959,29,10,1.118108,-0.258605,-0.103982,-0.231256,0.344866,-0.223807,-0.014415,-0.046215,-0.219385,0.013357,-0.010018,0.192860,N
9960,29,11,1.177449,-0.404080,0.052026,-0.284812,0.429840,-0.203484,-0.072393,-0.080955,-0.244424,-0.001849,-0.016634,0.224688,N

In [66]:
df.isna().sum().sum()

np.int64(0)

In [68]:
df.drop(columns=["utterance", "frame"], inplace=True)

In [ ]:
df = df.rename(columns={"binaryClass": "target"})
df["target"] = (df["target"] == "P").astype(int)

In [74]:
df["target"].value_counts()
df

,coefficient1,coefficient2,coefficient3,coefficient4,coefficient5,coefficient6,coefficient7,coefficient8,coefficient9,coefficient10,coefficient11,coefficient12,target
0,1.860936,-0.207383,0.261557,-0.214562,-0.171253,-0.118167,-0.277557,0.025668,0.126701,-0.306756,-0.213076,0.088728,0
1,1.891651,-0.193249,0.235363,-0.249118,-0.112890,-0.112238,-0.311997,-0.027122,0.171457,-0.289431,-0.247722,0.093011,0
2,1.939205,-0.239664,0.258561,-0.291458,-0.041053,-0.102034,-0.383300,0.019013,0.169510,-0.314894,-0.227908,0.074638,0
3,1.717517,-0.218572,0.217119,-0.228186,-0.018608,-0.137624,-0.403318,-0.009643,0.164607,-0.323267,-0.210105,0.098098,0
4,1.741191,-0.279891,0.196583,-0.236377,-0.032012,-0.090612,-0.363134,-0.012571,0.124298,-0.351171,-0.216545,0.113899,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9956,1.216506,-0.424432,-0.034349,-0.294238,0.166270,-0.397758,0.091827,0.023178,-0.191598,-0.111245,-0.011547,0.425088,0
9957,1.214579,-0.399925,-0.127891,-0.239583,0.221423,-0.374714,0.046216,0.051754,-0.197824,-0.099159,-0.018177,0.359986,0
9958,1.170031,-0.306025,-0.145534,-0.195854,0.276371,-0.346794,0.042325,0.031668,-0.181205,-0.077962,-0.024079,0.305890,0
9959,1.118108,-0.258605,-0.103982,-0.231256,0.344866,-0.223807,-0.014415,-0.046215,-0.219385,0.013357,-0.010018,0.192860,0
9960,1.177449,-0.404080,0.052026,-0.284812,0.429840,-0.203484,-0.072393,-0.080955,-0.244424,-0.001849,-0.016634,0.224688,0

# 7

In [80]:
df = pd.read_csv("../class_imbalance/dataset_1020_mfeat-karhunen.csv")
df

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att56,att57,att58,att59,att60,att61,att62,att63,att64,binaryClass
0,-10.297008,-11.666789,11.560669,-2.081316,4.044656,4.086815,-2.558072,-8.476935,2.138135,3.503082,...,0.921927,0.496387,-0.643667,0.284104,0.286555,0.348625,1.814691,-1.351353,-0.473910,P
1,-5.036009,-12.885333,0.161155,0.592460,3.123534,4.220469,-6.411771,-6.335328,-0.244622,1.346073,...,2.938791,1.429883,-2.336344,1.281628,-0.098321,0.582357,0.485792,0.642451,0.613107,P
2,-9.639157,-6.655898,0.388687,-1.717650,0.300346,3.400769,-7.240785,-1.659405,-0.874005,4.153403,...,-0.023028,-0.025265,1.259838,-0.441360,-0.960094,1.995843,1.097748,0.827182,-1.767840,P
3,-6.650375,-7.043851,4.104350,-2.342780,3.494658,3.924822,-9.874812,-6.556576,-1.364269,1.153308,...,-1.043815,-0.204508,-1.981150,0.982438,-0.144233,-1.449328,-0.913552,-0.771735,0.304992,P
4,-10.664524,-10.974133,0.194391,0.453885,2.193088,-3.304663,-8.376592,-4.241146,2.964818,-0.949622,...,1.448160,-1.254907,-3.481295,-0.563889,1.529335,0.510399,0.298318,-0.943213,1.149847,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-2.415248,-6.619806,5.053538,6.662300,12.136673,-1.447842,-2.321873,4.042169,-2.981806,-0.106785,...,-0.714285,0.017051,0.460572,-0.951763,0.241901,-0.399051,-0.304857,-0.068411,-1.049052,N
1996,5.892684,-8.185875,1.819305,6.871263,1.021333,-0.869375,-6.759738,-3.891993,-4.781352,3.355656,...,1.273016,0.227573,0.444086,1.439473,-0.405706,0.378187,-0.128056,0.925637,1.798054,N
1997,1.881613,-9.650881,0.317780,0.655888,7.882648,1.740497,0.026943,-4.412813,-3.403179,-0.614610,...,-1.622687,0.309964,0.473773,0.916683,0.971719,0.689472,-0.439637,0.287013,-0.420793,N
1998,-1.530886,-10.183775,-1.055864,4.956079,11.729954,1.480784,-2.806543,0.602515,-5.411981,-2.165543,...,-0.466334,0.128358,-0.888494,-0.014442,-0.780897,1.000286,1.405214,0.435514,-0.225426,N
1999,11.251634,-5.959691,5.367245,-0.841945,3.711649,-0.073462,-1.145635,1.658259,-5.050816,0.696735,...,-1.142042,1.895628,0.006474,-1.050163,-1.206900,0.997437,0.007912,0.763971,0.040369,N

In [81]:
df.isna().sum().sum()

np.int64(0)

In [83]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns,
    index=X.index
)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att56,att57,att58,att59,att60,att61,att62,att63,att64,binaryClass
0,-1.193540,-1.921575,1.836540,-0.674990,0.288871,0.930293,-0.282909,-2.096582,0.581647,1.394894,...,0.764281,0.464313,-0.492619,0.463989,0.468077,0.402956,2.072242,-1.783580,-0.285174,P
1,-0.509350,-2.134793,-0.208981,-0.189396,0.058191,0.969349,-1.230752,-1.464631,0.011385,0.829627,...,2.528923,1.424693,-2.163978,1.563687,0.101491,0.660444,0.595197,0.451323,0.776526,P
2,-1.107987,-1.044785,-0.168152,-0.608943,-0.648830,0.729818,-1.434654,-0.084848,-0.139245,1.565318,...,-0.062500,-0.072363,1.386912,-0.335783,-0.719329,2.217596,1.275374,0.658393,-1.548967,P
3,-0.719297,-1.112668,0.498583,-0.722475,0.151133,0.882955,-2.082511,-1.529917,-0.256579,0.779111,...,-0.955631,-0.256768,-1.813257,1.233852,0.057761,-1.577740,-0.960147,-1.133872,0.475587,P
4,-1.241335,-1.800377,-0.203017,-0.214563,-0.174823,-1.229626,-1.714013,-0.846675,0.779496,0.228015,...,1.224705,-1.337418,-3.294509,-0.470862,1.651797,0.581172,0.386823,-1.326086,1.300765,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-0.168521,-1.038469,0.668905,0.912968,2.315384,-0.687031,-0.224814,1.597586,-0.643702,0.448890,...,-0.667311,-0.028828,0.597713,-0.898465,0.425545,-0.420714,-0.283595,-0.345499,-0.846920,N
1996,0.911921,-1.312495,0.088557,0.950918,-0.468270,-0.517993,-1.316337,-0.743646,-1.074385,1.356260,...,1.071464,0.187757,0.581434,1.737700,-0.191287,0.435522,-0.087084,0.768753,1.933875,N
1997,0.390283,-1.568838,-0.180876,-0.177877,1.250033,0.244658,0.352893,-0.897331,-0.744549,0.315809,...,-1.462111,0.272521,0.610747,1.161361,1.120680,0.778446,-0.433400,0.052904,-0.233294,N
1998,-0.053511,-1.662082,-0.427362,0.603095,2.213528,0.168765,-0.344022,0.582604,-1.225313,-0.090630,...,-0.450368,0.085685,-0.734363,0.134863,-0.548648,1.120851,1.617116,0.219363,-0.042477,N
1999,1.608849,-0.922964,0.725196,-0.449903,0.205475,-0.285413,0.064490,0.894136,-1.138876,0.659461,...,-1.041574,1.903851,0.149334,-1.006944,-0.954406,1.117712,0.064042,0.587538,0.217127,N

In [84]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})

#df_scaled

target
N    1800
P     200
Name: count, dtype: int64

In [85]:
df_scaled["target"] = (df_scaled["target"] == "P").astype(int)
df_scaled['target'].value_counts()

target
0    1800
1     200
Name: count, dtype: int64

In [86]:
df_scaled

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att56,att57,att58,att59,att60,att61,att62,att63,att64,target
0,-1.193540,-1.921575,1.836540,-0.674990,0.288871,0.930293,-0.282909,-2.096582,0.581647,1.394894,...,0.764281,0.464313,-0.492619,0.463989,0.468077,0.402956,2.072242,-1.783580,-0.285174,1
1,-0.509350,-2.134793,-0.208981,-0.189396,0.058191,0.969349,-1.230752,-1.464631,0.011385,0.829627,...,2.528923,1.424693,-2.163978,1.563687,0.101491,0.660444,0.595197,0.451323,0.776526,1
2,-1.107987,-1.044785,-0.168152,-0.608943,-0.648830,0.729818,-1.434654,-0.084848,-0.139245,1.565318,...,-0.062500,-0.072363,1.386912,-0.335783,-0.719329,2.217596,1.275374,0.658393,-1.548967,1
3,-0.719297,-1.112668,0.498583,-0.722475,0.151133,0.882955,-2.082511,-1.529917,-0.256579,0.779111,...,-0.955631,-0.256768,-1.813257,1.233852,0.057761,-1.577740,-0.960147,-1.133872,0.475587,1
4,-1.241335,-1.800377,-0.203017,-0.214563,-0.174823,-1.229626,-1.714013,-0.846675,0.779496,0.228015,...,1.224705,-1.337418,-3.294509,-0.470862,1.651797,0.581172,0.386823,-1.326086,1.300765,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-0.168521,-1.038469,0.668905,0.912968,2.315384,-0.687031,-0.224814,1.597586,-0.643702,0.448890,...,-0.667311,-0.028828,0.597713,-0.898465,0.425545,-0.420714,-0.283595,-0.345499,-0.846920,0
1996,0.911921,-1.312495,0.088557,0.950918,-0.468270,-0.517993,-1.316337,-0.743646,-1.074385,1.356260,...,1.071464,0.187757,0.581434,1.737700,-0.191287,0.435522,-0.087084,0.768753,1.933875,0
1997,0.390283,-1.568838,-0.180876,-0.177877,1.250033,0.244658,0.352893,-0.897331,-0.744549,0.315809,...,-1.462111,0.272521,0.610747,1.161361,1.120680,0.778446,-0.433400,0.052904,-0.233294,0
1998,-0.053511,-1.662082,-0.427362,0.603095,2.213528,0.168765,-0.344022,0.582604,-1.225313,-0.090630,...,-0.450368,0.085685,-0.734363,0.134863,-0.548648,1.120851,1.617116,0.219363,-0.042477,0
1999,1.608849,-0.922964,0.725196,-0.449903,0.205475,-0.285413,0.064490,0.894136,-1.138876,0.659461,...,-1.041574,1.903851,0.149334,-1.006944,-0.954406,1.117712,0.064042,0.587538,0.217127,0

# 8

In [87]:
df = pd.read_csv("../class_imbalance/dataset_1022_mfeat-pixel.csv")
df

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att232,att233,att234,att235,att236,att237,att238,att239,att240,binaryClass
0,0,3,4,4,6,6,6,6,6,5,...,4,4,4,4,3,0,0,0,0,P
1,0,0,0,0,0,0,1,3,4,4,...,4,4,4,4,2,0,0,0,0,P
2,0,0,1,4,4,4,4,4,4,3,...,3,4,4,4,4,4,2,1,0,P
3,0,0,3,3,2,2,4,5,6,6,...,4,4,4,2,0,0,0,0,0,P
4,0,0,0,0,0,0,3,4,6,6,...,4,4,4,3,1,0,0,0,0,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,0,1,3,4,5,6,4,4,...,4,4,4,4,4,4,0,0,0,N
1996,0,0,0,0,3,6,6,6,6,6,...,4,4,3,0,0,0,0,0,0,N
1997,0,0,0,2,4,4,4,6,4,4,...,2,4,4,4,1,0,0,0,0,N
1998,0,0,0,0,0,0,2,4,4,5,...,4,4,4,4,2,0,0,0,0,N
1999,0,0,1,5,6,6,6,6,6,6,...,4,1,0,0,0,0,0,0,0,N

In [89]:
df.isna().sum().sum()

np.int64(0)

In [90]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att232,att233,att234,att235,att236,att237,att238,att239,att240,binaryClass
0,-0.399921,0.782056,0.793669,0.504411,1.091416,0.965258,0.869469,0.860472,0.879291,0.477674,...,0.675205,0.648492,0.660891,0.741783,0.276071,-1.142643,-0.843260,-0.593274,-0.368305,P
1,-0.399921,-0.627477,-0.868030,-1.137285,-1.423851,-1.712915,-1.484263,-0.602501,-0.087228,0.023611,...,0.675205,0.648492,0.660891,0.741783,-0.290810,-1.142643,-0.843260,-0.593274,-0.368305,P
2,-0.399921,-0.627477,-0.452605,0.504411,0.252994,0.072534,-0.072024,-0.114843,-0.087228,-0.430451,...,0.087559,0.648492,0.660891,0.741783,0.842952,1.048952,0.272532,0.052994,-0.368305,P
3,-0.399921,-0.627477,0.378244,0.093987,-0.585428,-0.820190,-0.072024,0.372814,0.879291,0.931737,...,0.675205,0.648492,0.660891,-0.454159,-1.424572,-1.142643,-0.843260,-0.593274,-0.368305,P
4,-0.399921,-0.627477,-0.868030,-1.137285,-1.423851,-1.712915,-0.542771,-0.114843,0.879291,0.931737,...,0.675205,0.648492,0.660891,0.143812,-0.857691,-1.142643,-0.843260,-0.593274,-0.368305,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-0.399921,-0.627477,-0.868030,-0.726861,-0.166217,0.072534,0.398722,0.860472,-0.087228,0.023611,...,0.675205,0.648492,0.660891,0.741783,0.842952,1.048952,-0.843260,-0.593274,-0.368305,N
1996,-0.399921,-0.627477,-0.868030,-1.137285,-0.166217,0.965258,0.869469,0.860472,0.879291,0.931737,...,0.675205,0.648492,0.053733,-1.650101,-1.424572,-1.142643,-0.843260,-0.593274,-0.368305,N
1997,-0.399921,-0.627477,-0.868030,-0.316437,0.252994,0.072534,-0.072024,0.860472,-0.087228,0.023611,...,-0.500087,0.648492,0.660891,0.741783,-0.857691,-1.142643,-0.843260,-0.593274,-0.368305,N
1998,-0.399921,-0.627477,-0.868030,-1.137285,-1.423851,-1.712915,-1.013517,-0.114843,-0.087228,0.477674,...,0.675205,0.648492,0.660891,0.741783,-0.290810,-1.142643,-0.843260,-0.593274,-0.368305,N
1999,-0.399921,-0.627477,-0.452605,0.914835,1.091416,0.965258,0.869469,0.860472,0.879291,0.931737,...,0.675205,-1.180822,-1.767740,-1.650101,-1.424572,-1.142643,-0.843260,-0.593274,-0.368305,N

In [91]:
df_scaled["binaryClass"].value_counts()

binaryClass
N    1800
P     200
Name: count, dtype: int64

In [92]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled["target"] = (df_scaled["target"] == "P").astype(int)

## 9

In [94]:
df = pd.read_csv("../class_imbalance/dataset_980_optdigits.csv")
df

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,...,input56,input57,input58,input59,input60,input61,input62,input63,input64,binaryClass
0,0,1,6,15,12,1,0,0,0,7,...,0,0,0,6,14,7,1,0,0,N
1,0,0,10,16,6,0,0,0,0,7,...,0,0,0,10,16,15,3,0,0,N
2,0,0,8,15,16,13,0,0,0,1,...,0,0,0,9,14,0,0,0,0,N
3,0,0,0,3,11,16,0,0,0,0,...,0,0,0,0,1,15,2,0,0,N
4,0,0,5,14,4,0,0,0,0,0,...,0,0,0,4,12,14,7,0,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5615,0,0,4,10,13,6,0,0,0,1,...,0,0,0,2,14,15,9,0,0,N
5616,0,0,6,16,13,11,1,0,0,0,...,0,0,0,6,16,14,6,0,0,N
5617,0,0,1,11,15,1,0,0,0,0,...,0,0,0,2,9,13,6,0,0,N
5618,0,0,2,10,7,0,0,0,0,0,...,0,0,0,5,12,16,12,0,0,N
5619,0,0,10,14,8,1,0,0,0,2,...,0,0,1,8,12,14,12,1,0,N

In [96]:
df.isna().sum().sum()

np.int64(0)

In [95]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,...,input56,input57,input58,input59,input60,input61,input62,input63,input64,binaryClass
0,0.0,0.793133,0.129863,0.748317,0.094508,-0.815851,-0.410972,-0.132062,-0.035424,1.622966,...,-0.197899,-0.018868,-0.303102,0.047703,0.462445,-0.919036,-0.983796,-0.517244,-0.179136,N
1,0.0,-0.343381,0.985972,0.983303,-1.250136,-0.993451,-0.410972,-0.132062,-0.035424,1.622966,...,-0.197899,-0.018868,-0.303102,0.844405,0.922516,0.688929,-0.639861,-0.517244,-0.179136,N
2,0.0,-0.343381,0.557918,0.748317,0.990937,1.315342,-0.410972,-0.132062,-0.035424,-0.313430,...,-0.197899,-0.018868,-0.303102,0.645229,0.462445,-2.326006,-1.155764,-0.517244,-0.179136,N
3,0.0,-0.343381,-1.154300,-2.071514,-0.129599,1.848140,-0.410972,-0.132062,-0.035424,-0.636162,...,-0.197899,-0.018868,-0.303102,-1.147350,-2.528016,0.688929,-0.811828,-0.517244,-0.179136,N
4,0.0,-0.343381,-0.084164,0.513331,-1.698350,-0.993451,-0.410972,-0.132062,-0.035424,-0.636162,...,-0.197899,-0.018868,-0.303102,-0.350648,0.002374,0.487933,0.048010,-0.517244,-0.179136,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5615,0.0,-0.343381,-0.298191,-0.426612,0.318615,0.072146,-0.410972,-0.132062,-0.035424,-0.313430,...,-0.197899,-0.018868,-0.303102,-0.748999,0.462445,0.688929,0.391946,-0.517244,-0.179136,N
5616,0.0,-0.343381,0.129863,0.983303,0.318615,0.960143,-0.113028,-0.132062,-0.035424,-0.636162,...,-0.197899,-0.018868,-0.303102,0.047703,0.922516,0.487933,-0.123957,-0.517244,-0.179136,N
5617,0.0,-0.343381,-0.940273,-0.191626,0.766830,-0.815851,-0.410972,-0.132062,-0.035424,-0.636162,...,-0.197899,-0.018868,-0.303102,-0.748999,-0.687732,0.286937,-0.123957,-0.517244,-0.179136,N
5618,0.0,-0.343381,-0.726245,-0.426612,-1.026028,-0.993451,-0.410972,-0.132062,-0.035424,-0.636162,...,-0.197899,-0.018868,-0.303102,-0.151473,0.002374,0.889924,0.907849,-0.517244,-0.179136,N
5619,0.0,-0.343381,0.985972,0.513331,-0.801921,-0.815851,-0.410972,-0.132062,-0.035424,0.009303,...,-0.197899,-0.018868,0.772298,0.446054,0.002374,0.487933,0.907849,-0.270183,-0.179136,N

In [97]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled["target"].value_counts()

target
N    5048
P     572
Name: count, dtype: int64

In [98]:
df_scaled["target"] = (df_scaled["target"] == "P").astype(int)

# 10

In [99]:
df = pd.read_csv("../class_imbalance/dataset_954_spectrometer.csv")
df

,ID-type,Right-Ascension,Declination,Scale_Factor,Blue_base_1,Blue_base_2,Red_base_1,Red_base_2,blue-band-flux_1,blue-band-flux_2,...,red-band-flux_41,red-band-flux_42,red-band-flux_43,red-band-flux_44,red-band-flux_45,red-band-flux_46,red-band-flux_47,red-band-flux_48,red-band-flux_49,binaryClass
0,2,12.073,-62.428,0,2498.0,2630.0,1740.0,1783.0,4119.1675,4897.2990,...,2039.33590,1891.61340,1040.11570,1211.53580,1767.62330,1146.94710,1392.47450,1278.99450,1440.48200,N
1,3,12.106,-62.987,0,1086.0,1241.0,421.0,674.0,7660.9990,7906.7840,...,7056.40530,6817.42970,6682.79440,6988.59770,7084.03600,6971.78300,7015.57470,6962.22000,6263.44000,N
2,3,12.123,-62.554,0,481.0,270.0,63.0,451.0,3196.4287,3013.9722,...,6998.41550,6669.61100,6551.05900,6679.77150,6564.26300,6309.63960,5954.38800,5337.88870,4638.52440,N
3,4,12.247,-67.683,0,191.0,232.0,103.0,103.0,26028.4510,23706.8140,...,507.43262,446.32816,417.10430,454.29834,448.98490,459.61176,409.13416,366.62670,332.08942,N
4,0,12.360,-62.303,0,1401.0,1268.0,1042.0,1063.0,15835.3850,15097.6970,...,664.50507,909.68350,837.53380,862.60760,693.25110,890.75964,473.78302,658.46140,725.74945,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,2,23.819,62.732,0,1315.0,1495.0,843.0,810.0,14111.7340,14462.1270,...,883.77320,998.42004,735.88940,1088.73080,687.22630,686.34280,934.49110,933.59190,501.37790,N
527,4,23.827,61.526,0,238.0,280.0,99.0,142.0,8702.8700,8777.9060,...,1423.84380,1320.31090,1279.61380,1284.83720,1236.90540,1208.31240,1203.89100,1099.19290,1037.99740,N
528,4,23.881,48.360,0,577.0,568.0,416.0,431.0,15375.6040,14542.2330,...,1025.80850,795.37830,767.25446,802.76160,843.16656,642.11680,824.46655,703.36536,649.15760,N
529,3,23.902,70.526,0,995.0,1177.0,463.0,398.0,11814.4600,12896.9450,...,1970.82130,1748.14440,1757.16270,1724.30970,1721.34130,1546.44600,1677.99240,1601.73520,1470.15520,N
530,2,23.941,-56.854,0,562.0,640.0,309.0,339.0,14268.0370,12925.0450,...,951.77560,881.81370,797.37744,795.00860,757.24786,695.35840,702.66327,681.01196,670.62964,N

In [101]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled

,ID-type,Right-Ascension,Declination,Scale_Factor,Blue_base_1,Blue_base_2,Red_base_1,Red_base_2,blue-band-flux_1,blue-band-flux_2,...,red-band-flux_41,red-band-flux_42,red-band-flux_43,red-band-flux_44,red-band-flux_45,red-band-flux_46,red-band-flux_47,red-band-flux_48,red-band-flux_49,target
0,-0.244330,-2.045064,-1.226828,0.0,2.829533,2.958914,3.562730,3.526146,-1.531842,-1.460297,...,0.482594,0.458986,-0.259949,-0.118371,0.378102,-0.108773,0.119164,0.075082,0.379365,N
1,0.345394,-2.033620,-1.239871,0.0,0.393908,0.601449,-0.188023,0.426705,-0.887637,-0.861583,...,4.737639,4.819858,4.677256,4.780663,4.895372,4.929176,4.927393,5.137302,5.363975,N
2,0.345394,-2.027725,-1.229768,0.0,-0.649684,-1.046570,-1.206043,-0.196536,-1.699674,-1.834971,...,4.688457,4.688992,4.561991,4.518774,4.453729,4.356483,4.019988,3.690461,3.684597,N
3,0.935118,-1.984723,-1.349445,0.0,-1.149919,-1.111065,-1.092298,-1.169129,2.453125,2.281715,...,-0.816635,-0.820539,-0.805068,-0.760520,-0.742323,-0.703255,-0.721675,-0.737591,-0.766178,N
4,-1.423778,-1.945537,-1.223911,0.0,0.937266,0.647275,1.577874,1.513885,0.599161,0.568995,...,-0.683419,-0.410326,-0.437203,-0.414268,-0.534774,-0.330352,-0.666395,-0.477645,-0.359324,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,-0.244330,2.028279,1.693596,0.0,0.788921,1.032548,1.011991,0.806799,0.285655,0.442554,...,-0.497455,-0.331767,-0.526139,-0.222512,-0.539893,-0.507154,-0.272450,-0.232578,-0.591215,N
527,0.935118,2.031053,1.665456,0.0,-1.068846,-1.029598,-1.103672,-1.060132,-0.698136,-0.688280,...,-0.039414,-0.046794,-0.050394,-0.056211,-0.072840,-0.055698,-0.042091,-0.085073,-0.036610,N
528,0.935118,2.049779,1.358246,0.0,-0.484090,-0.540793,-0.202241,-0.252433,0.515533,0.458490,...,-0.376993,-0.511522,-0.498695,-0.465018,-0.407394,-0.545405,-0.366531,-0.437648,-0.438483,N
529,0.345394,2.057062,1.875457,0.0,0.236938,0.492826,-0.068590,-0.344661,-0.132185,0.131172,...,0.424485,0.331971,0.367450,0.316468,0.338777,0.236757,0.363306,0.362557,0.410033,N
530,-0.244330,2.070586,-1.096767,0.0,-0.509964,-0.418592,-0.506509,-0.509555,0.314084,0.136763,...,-0.439781,-0.434999,-0.472339,-0.471593,-0.480397,-0.499356,-0.470683,-0.457559,-0.416291,N

In [ ]:
df_scaled["target"] = (df_scaled["target"] == "P").astype(int)

# 11

In [113]:
df = pd.read_csv("../class_imbalance/dataset_1021_page-blocks.csv")
df

,height,lenght,area,eccen,p_black,p_and,mean_tr,blackpix,blackand,wb_trans,binaryClass
0,5.0,7.0,35.0,1.400,0.400,0.657,2.33,14.0,23.0,6.0,P
1,6.0,7.0,42.0,1.167,0.429,0.881,3.60,18.0,37.0,5.0,P
2,6.0,18.0,108.0,3.000,0.287,0.741,4.43,31.0,80.0,7.0,P
3,5.0,7.0,35.0,1.400,0.371,0.743,4.33,13.0,26.0,3.0,P
4,6.0,3.0,18.0,0.500,0.500,0.944,2.25,9.0,17.0,4.0,P
...,...,...,...,...,...,...,...,...,...,...,...
5468,4.0,524.0,2096.0,131.000,0.542,0.603,40.57,1136.0,1264.0,28.0,N
5469,7.0,4.0,28.0,0.571,0.714,0.929,10.00,20.0,26.0,2.0,P
5470,6.0,95.0,570.0,15.833,0.300,0.911,1.64,171.0,519.0,104.0,P
5471,7.0,41.0,287.0,5.857,0.213,0.801,1.36,61.0,230.0,45.0,P
5472,8.0,1.0,8.0,0.125,1.000,1.000,8.00,8.0,8.0,1.0,N

In [115]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,height,lenght,area,eccen,p_black,p_and,mean_tr,blackpix,blackand,wb_trans,binaryClass
0,-0.288690,-0.719792,-0.239930,-0.402397,0.176423,-0.750401,-0.056307,-0.277063,-0.381702,-0.601716,P
1,-0.235945,-0.719792,-0.238487,-0.409987,0.339583,0.562261,-0.037921,-0.273914,-0.374260,-0.607693,P
2,-0.235945,-0.623899,-0.224875,-0.350282,-0.459335,-0.258153,-0.025904,-0.263680,-0.351404,-0.595738,P
3,-0.288690,-0.719792,-0.239930,-0.402397,0.013264,-0.246432,-0.027352,-0.277851,-0.380107,-0.619648,P
4,-0.235945,-0.754662,-0.243436,-0.431713,0.739041,0.931447,-0.057465,-0.281000,-0.384891,-0.613671,P
...,...,...,...,...,...,...,...,...,...,...,...
5468,-0.341436,3.787176,0.185112,3.818973,0.975341,-1.066846,0.497312,0.606250,0.277937,-0.470210,N
5469,-0.183199,-0.745944,-0.241374,-0.429400,1.943044,0.843545,0.054735,-0.272340,-0.380107,-0.625626,P
5470,-0.235945,0.047352,-0.129597,0.067719,-0.386195,0.738064,-0.066296,-0.153463,-0.118059,-0.015918,P
5471,-0.183199,-0.423396,-0.187960,-0.257223,-0.875672,0.093453,-0.070350,-0.240062,-0.271674,-0.368592,P
5472,-0.130453,-0.772097,-0.245498,-0.443927,3.552131,1.259612,0.025780,-0.281787,-0.389675,-0.631603,N

In [116]:
df["binaryClass"].value_counts()

binaryClass
P    4913
N     560
Name: count, dtype: int64

In [ ]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled["target"] = (df_scaled["target"] == "N").astype(int)

In [118]:
df_scaled["target"].value_counts()

target
0    4913
1     560
Name: count, dtype: int64

# 12

In [127]:
df = pd.read_csv("../class_imbalance/dataset_958_segment.csv")
df

,region-centroid-col,region-centroid-row,region-pixel-count,short-line-density-5,short-line-density-2,vedge-mean,vegde-sd,hedge-mean,hedge-sd,intensity-mean,rawred-mean,rawblue-mean,rawgreen-mean,exred-mean,exblue-mean,exgreen-mean,value-mean,saturation-mean,hue-mean,binaryClass
0,218,178,9,0.111111,0.0,0.833333,0.547722,1.111110,0.544331,59.629600,52.44440,75.22220,51.222200,-21.555600,46.77780,-25.22220,75.22220,0.318996,-2.04055,N
1,113,130,9,0.000000,0.0,0.277778,0.250924,0.333333,0.365148,0.888889,0.00000,2.55556,0.111111,-2.666670,5.00000,-2.33333,2.55556,1.000000,-2.12325,N
2,202,41,9,0.000000,0.0,0.944448,0.772202,1.111110,1.025600,123.037000,111.88900,139.77800,117.444000,-33.444400,50.22220,-16.77780,139.77800,0.199347,-2.29992,N
3,32,173,9,0.000000,0.0,1.722220,1.781590,9.000000,6.749490,43.592600,39.55560,52.88890,38.333300,-12.111100,27.88890,-15.77780,52.88890,0.266914,-1.99886,N
4,61,197,9,0.000000,0.0,1.444440,1.515350,2.611110,1.925460,49.592600,44.22220,61.55560,43.000000,-16.111100,35.88890,-19.77780,61.55560,0.302925,-2.02227,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,30,102,9,0.000000,0.0,1.222220,0.118518,1.333330,0.800000,20.259300,20.33330,25.00000,15.444400,0.222222,14.22220,-14.44440,25.00000,0.381059,-1.55510,P
2306,143,24,9,0.000000,0.0,1.277780,0.907406,0.888888,1.140750,127.630000,117.66700,141.66700,123.556000,-29.888900,42.11110,-12.22220,141.66700,0.169397,-2.34925,N
2307,80,72,9,0.000000,0.0,1.222220,1.003700,1.444440,1.167460,59.000000,51.33330,74.44440,51.222200,-23.000000,46.33330,-23.33330,74.44440,0.314606,-2.09022,N
2308,98,133,9,0.000000,0.0,0.555555,0.172133,0.388889,0.327731,0.962963,0.00000,2.77778,0.111111,-2.888890,5.44444,-2.55556,2.77778,1.000000,-2.12325,N
2309,19,147,9,0.000000,0.0,0.222222,0.074074,0.500000,0.077778,4.148150,3.88889,6.66667,1.888890,-0.777778,7.55556,-6.77778,7.00000,0.713228,-1.47564,P

In [128]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,region-centroid-col,region-centroid-row,region-pixel-count,short-line-density-5,short-line-density-2,vedge-mean,vegde-sd,hedge-mean,hedge-sd,intensity-mean,rawred-mean,rawblue-mean,rawgreen-mean,exred-mean,exblue-mean,exgreen-mean,value-mean,saturation-mean,hue-mean,binaryClass
0,1.276189,0.949736,0.0,2.410668,-0.194552,-0.393061,-0.115120,-0.363952,-0.130944,0.591541,0.560193,0.713137,0.469693,-0.765452,1.296479,-1.429044,0.701072,-0.472693,-0.438610,N
1,-0.163336,0.114538,0.0,-0.357047,-0.194552,-0.598950,-0.121739,-0.579445,-0.133992,-0.947458,-0.936970,-0.956668,-0.936122,0.865568,-0.838573,0.552826,-0.992297,2.510764,-0.492138,N
2,1.056833,-1.434058,0.0,-0.357047,-0.194552,-0.351882,-0.110113,-0.363952,-0.122759,2.252805,2.257194,2.196563,2.291130,-1.792025,1.472504,-0.697872,2.205432,-0.996872,-0.606487,N
3,-1.273827,0.862737,0.0,-0.357047,-0.194552,-0.063639,-0.087601,1.821759,-0.025412,0.171373,0.192248,0.199941,0.115183,0.050061,0.331163,-0.611285,0.180634,-0.700863,-0.411626,N
4,-0.876244,1.280336,0.0,-0.357047,-0.194552,-0.166585,-0.093539,0.051641,-0.107455,0.328573,0.325468,0.399093,0.243541,-0.295331,0.740002,-0.957632,0.382596,-0.543100,-0.426778,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,-1.301246,-0.372660,0.0,-0.357047,-0.194552,-0.248940,-0.124692,-0.302384,-0.126596,-0.439956,-0.356503,-0.440918,-0.514378,1.115018,-0.367273,-0.495831,-0.469268,-0.200797,-0.124403,P
2306,0.247957,-1.729857,0.0,-0.357047,-0.194552,-0.228349,-0.107098,-0.425521,-0.120801,2.373141,2.422142,2.239971,2.459241,-1.485015,1.057987,-0.303418,2.249452,-1.128082,-0.638416,N
2307,-0.615758,-0.894659,0.0,-0.357047,-0.194552,-0.248940,-0.104950,-0.271599,-0.120347,0.575045,0.528473,0.695264,0.469693,-0.890173,1.273762,-1.265490,0.682947,-0.491926,-0.470759,N
2308,-0.368982,0.166738,0.0,-0.357047,-0.194552,-0.496006,-0.123497,-0.564052,-0.134628,-0.945517,-0.936970,-0.951562,-0.936122,0.846380,-0.815860,0.533584,-0.987118,2.510764,-0.492138,N
2309,-1.452053,0.410338,0.0,-0.357047,-0.194552,-0.619539,-0.125684,-0.533268,-0.138879,-0.862066,-0.825952,-0.862199,-0.887224,1.028670,-0.707971,0.167996,-0.888727,1.254425,-0.072973,P

In [129]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled["target"].value_counts()

target
N    1980
P     330
Name: count, dtype: int64

In [131]:
df_scaled["target"] = (df_scaled["target"] == "P").astype(int)

In [132]:
df_scaled["target"].value_counts()

target
0    1980
1     330
Name: count, dtype: int64

# 13

In [154]:
df = pd.read_csv("../class_imbalance/dataset_865_analcatdata_neavote.csv")
df

   Party  Favorable binaryClass
0      R          1           N
1      R          1           N
2      R          2           N
3      R          2           N
4      R          2           P
..   ...        ...         ...
95     D         10           N
96     D         10           N
97     D         10           N
98     R          1           N
99     R          1           N

[100 rows x 3 columns]

In [155]:
categorical_cols = ["Party"]
df_dummies = pd.get_dummies(df, columns=categorical_cols, drop_first=True, dtype=int)
df_dummies

    Favorable binaryClass  Party_I  Party_R
0           1           N        0        1
1           1           N        0        1
2           2           N        0        1
3           2           N        0        1
4           2           P        0        1
..        ...         ...      ...      ...
95         10           N        0        0
96         10           N        0        0
97         10           N        0        0
98          1           N        0        1
99          1           N        0        1

[100 rows x 4 columns]

In [137]:
df.isna().sum()

Party          0
Favorable      0
binaryClass    0
dtype: int64

In [138]:
df_dummies = df_dummies.rename(columns={"binaryClass": "target"})
df_dummies["target"].value_counts()

target
N    93
P     7
Name: count, dtype: int64

In [ ]:
df_dummies["target"] = (df_dummies["target"] == "P").astype(int)

# 14

In [141]:
df = pd.read_csv("../class_imbalance/dataset_1013_analcatdata_challenger.csv")
df

     Temperature  Pressure  Damaged
0             66        50        0
1             66        50        0
2             66        50        0
3             66        50        0
4             66        50        0
..           ...       ...      ...
133           58       200        0
134           58       200        0
135           58       200        0
136           58       200        0
137           58       200        0

[138 rows x 3 columns]

In [143]:
X = df.drop(columns=["Damaged"])
y = df["Damaged"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["Damaged"] = y
df_scaled

     Temperature  Pressure  Damaged
0      -0.516551 -1.531343        0
1      -0.516551 -1.531343        0
2      -0.516551 -1.531343        0
3      -0.516551 -1.531343        0
4      -0.516551 -1.531343        0
..           ...       ...      ...
133    -1.675642  0.716799        0
134    -1.675642  0.716799        0
135    -1.675642  0.716799        0
136    -1.675642  0.716799        0
137    -1.675642  0.716799        0

[138 rows x 3 columns]

In [145]:
df["Damaged"].value_counts()
df_scaled = df_scaled.rename(columns={"Damaged": "target"})
df_scaled["target"] = (df_scaled["target"] == 1).astype(int)

KeyError: 'target'

In [146]:
df_scaled["target"].value_counts()

target
0    129
1      9
Name: count, dtype: int64

# 15

In [156]:
df = pd.read_csv("../class_imbalance/dataset_867_visualizing_livestock.csv")
df

    livestocktype         country binaryClass
0          Cattle         Albania           P
1          Cattle         Austria           P
2          Cattle         Belgium           P
3          Cattle        Bulgaria           P
4          Cattle  Czechoslovakia           P
..            ...             ...         ...
125         Sheep     Switzerland           P
126         Sheep          Turkey           N
127         Sheep  United_Kingdom           N
128         Sheep   Russia_et_al.           N
129         Sheep      Yugoslavia           P

[130 rows x 3 columns]

In [157]:
categorical_cols = ["livestocktype", "country"]
df_dummies = pd.get_dummies(df, columns=categorical_cols, drop_first=True, dtype=int)
df_dummies = df_dummies.rename(columns={"binaryClass": "target"})
df_dummies

,target,livestocktype_Horses,livestocktype_Pigs,livestocktype_Poultry,livestocktype_Sheep,country_Austria,country_Belgium,country_Bulgaria,country_Czechoslovakia,country_Denmark,...,country_Portugal,country_Romania,country_Russia_et_al.,country_Spain,country_Sweden,country_Switzerland,country_Turkey,country_United_Kingdom,country_West_Germany,country_Yugoslavia
0,P,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,P,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,P,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,P,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,P,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,P,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
126,N,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
127,N,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
128,N,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
129,P,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [162]:
df_dummies["target"].value_counts()

target
P    105
N     25
Name: count, dtype: int64

In [164]:
df_dummies["target"] = (df_dummies["target"] == "N").astype(int)
df_dummies["target"].value_counts()

target
0    105
1     25
Name: count, dtype: int64

# 16

In [165]:
df = pd.read_csv("../class_imbalance/dataset_875_analcatdata_chlamydia.csv")
df

      Age  Gender             Race binaryClass
0   10-14    Male            White           P
1   15-19    Male            White           N
2   20-24    Male            White           N
3   25-29    Male            White           P
4   30-34    Male            White           P
..    ...     ...              ...         ...
95  35-39  Female  American_Indian           P
96  40-44  Female  American_Indian           P
97  45-54  Female  American_Indian           P
98  55-64  Female  American_Indian           P
99    65+  Female  American_Indian           P

[100 rows x 4 columns]

In [166]:
categorical_cols = ["Age", "Gender", "Race"]
df_dummies = pd.get_dummies(df, columns=categorical_cols, drop_first=True, dtype=int)
df_dummies

,binaryClass,Age_15-19,Age_20-24,Age_25-29,Age_30-34,Age_35-39,Age_40-44,Age_45-54,Age_55-64,Age_65+,Gender_Male,Race_Asian/Pacific_Island,Race_Black,Race_Hispanic,Race_White
0,P,0,0,0,0,0,0,0,0,0,1,0,0,0,1
1,N,1,0,0,0,0,0,0,0,0,1,0,0,0,1
2,N,0,1,0,0,0,0,0,0,0,1,0,0,0,1
3,P,0,0,1,0,0,0,0,0,0,1,0,0,0,1
4,P,0,0,0,1,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,P,0,0,0,0,1,0,0,0,0,0,0,0,0,0
96,P,0,0,0,0,0,1,0,0,0,0,0,0,0,0
97,P,0,0,0,0,0,0,1,0,0,0,0,0,0,0
98,P,0,0,0,0,0,0,0,1,0,0,0,0,0,0
99,P,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [167]:
df_dummies = df_dummies.rename(columns={"binaryClass": "target"})
df_dummies["target"].value_counts()

target
P    81
N    19
Name: count, dtype: int64

# 17

In [168]:
df = pd.read_csv("../class_imbalance/dataset_764_analcatdata_apnea3.csv")
df

    Automatic Scorer_2  Subject binaryClass
0           N        N        1           N
1           H        N        1           P
2          OA        N        1           P
3          MA        N        1           P
4          CA        N        1           N
..        ...      ...      ...         ...
445         N       CA       18           P
446         H       CA       18           P
447        OA       CA       18           P
448        MA       CA       18           P
449        CA       CA       18           P

[450 rows x 4 columns]

In [169]:
categorical_cols = ["Automatic", "Scorer_2"]
df_dummies = pd.get_dummies(df, columns=categorical_cols, drop_first=True, dtype=int)
df_dummies

,Subject,binaryClass,Automatic_H,Automatic_MA,Automatic_N,Automatic_OA,Scorer_2_H,Scorer_2_MA,Scorer_2_N,Scorer_2_OA
0,1,N,0,0,1,0,0,0,1,0
1,1,P,1,0,0,0,0,0,1,0
2,1,P,0,0,0,1,0,0,1,0
3,1,P,0,1,0,0,0,0,1,0
4,1,N,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
445,18,P,0,0,1,0,0,0,0,0
446,18,P,1,0,0,0,0,0,0,0
447,18,P,0,0,0,1,0,0,0,0
448,18,P,0,1,0,0,0,0,0,0
449,18,P,0,0,0,0,0,0,0,0

In [170]:
X = df_dummies.drop(columns=["binaryClass"])
y = df_dummies["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,Subject,Automatic_H,Automatic_MA,Automatic_N,Automatic_OA,Scorer_2_H,Scorer_2_MA,Scorer_2_N,Scorer_2_OA,binaryClass
0,-1.638356,-0.5,-0.5,2.0,-0.5,-0.5,-0.5,2.0,-0.5,N
1,-1.638356,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,2.0,-0.5,P
2,-1.638356,-0.5,-0.5,-0.5,2.0,-0.5,-0.5,2.0,-0.5,P
3,-1.638356,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,2.0,-0.5,P
4,-1.638356,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,2.0,-0.5,N
...,...,...,...,...,...,...,...,...,...,...
445,1.638356,-0.5,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,P
446,1.638356,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,P
447,1.638356,-0.5,-0.5,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,P
448,1.638356,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,P
449,1.638356,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,P

In [171]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled["target"].value_counts()

target
P    395
N     55
Name: count, dtype: int64

In [173]:
df_scaled["target"] = (df_scaled["target"] == "N").astype(int)
df_scaled["target"].value_counts()

target
0    395
1     55
Name: count, dtype: int64

In [174]:
df_scaled

,Subject,Automatic_H,Automatic_MA,Automatic_N,Automatic_OA,Scorer_2_H,Scorer_2_MA,Scorer_2_N,Scorer_2_OA,target
0,-1.638356,-0.5,-0.5,2.0,-0.5,-0.5,-0.5,2.0,-0.5,1
1,-1.638356,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,2.0,-0.5,0
2,-1.638356,-0.5,-0.5,-0.5,2.0,-0.5,-0.5,2.0,-0.5,0
3,-1.638356,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,2.0,-0.5,0
4,-1.638356,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,2.0,-0.5,1
...,...,...,...,...,...,...,...,...,...,...
445,1.638356,-0.5,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,0
446,1.638356,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,0
447,1.638356,-0.5,-0.5,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,0
448,1.638356,-0.5,2.0,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,0
449,1.638356,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,-0.5,0

# 18

In [175]:
df = pd.read_csv("../class_imbalance/dataset_984_analcatdata_draft.csv")
df

,Lottery.pick.1970,Lottery.pick.1971,Month,Month.ordered.picks.1970,binaryClass
0,305.0,133.0,1,9,N
1,159.0,195.0,1,4,N
2,251.0,336.0,1,12,N
3,215.0,99.0,1,2,N
4,101.0,33.0,1,10,N
...,...,...,...,...,...
361,78.0,239.0,12,3,N
362,123.0,128.0,12,2,N
363,16.0,145.0,12,5,N
364,3.0,192.0,12,2,N
365,100.0,126.0,12,6,P

In [179]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

,Lottery.pick.1970,Lottery.pick.1971,Month,Month.ordered.picks.1970,binaryClass
0,1.149972,-0.474536,-1.597591,0.720420,N
1,-0.231887,0.113889,-1.597591,-0.728337,N
2,0.638874,1.452081,-1.597591,1.589675,N
3,0.298141,-0.797221,-1.597591,-1.307840,N
4,-0.780845,-1.423609,-1.597591,1.010172,N
...,...,...,...,...,...
361,-0.998536,0.531481,1.589675,-1.018088,N
362,-0.572620,-0.521990,1.589675,-1.307840,N
363,-1.585353,-0.360648,1.589675,-0.438586,N
364,-1.708395,0.085417,1.589675,-1.307840,N
365,-0.790310,-0.540971,1.589675,-0.148834,P

In [180]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled["target"].value_counts()

target
N    334
P     32
Name: count, dtype: int64

In [181]:
df_scaled["target"] = (df_scaled["target"] == "P").astype(int)
df_scaled["target"].value_counts()

target
0    334
1     32
Name: count, dtype: int64

# 19

In [183]:
df = pd.read_csv("../class_imbalance/dataset_1064_ar6.csv")
df

,total_loc,blank_loc,comment_loc,code_and_comment_loc,executable_loc,unique_operands,unique_operators,total_operands,total_operators,halstead_vocabulary,...,condition_count,multiple_condition_count,cyclomatic_complexity,cyclomatic_density,decision_density,design_complexity,design_density,normalized_cyclomatic_complexity,formal_parameters,defects
0,8,0,4,0,4,8,6,10,12,14,...,0,0,1,0.25,0.00,0.0,0.00,0.13,0.0,False
1,13,0,1,0,12,10,8,21,26,18,...,0,0,2,0.17,0.00,0.0,0.00,0.15,0.0,False
2,20,0,12,0,8,14,12,21,34,26,...,3,0,4,0.50,1.00,0.0,0.00,0.20,0.0,False
3,40,0,17,0,23,20,18,64,90,38,...,11,2,11,0.48,1.09,1.0,0.09,0.28,0.0,False
4,8,0,3,0,5,7,13,13,21,20,...,1,0,3,0.60,2.00,0.0,0.00,0.38,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,27,0,10,0,17,15,9,36,48,24,...,4,1,4,0.24,1.00,5.0,1.25,0.15,0.0,False
97,9,0,0,0,9,7,3,8,15,10,...,0,0,1,0.11,0.00,6.0,6.00,0.11,0.0,False
98,10,0,7,0,3,7,3,7,15,10,...,0,0,1,0.33,0.00,6.0,6.00,0.10,0.0,False
99,51,2,17,0,32,26,9,44,69,35,...,6,0,7,0.22,1.00,8.0,1.14,0.14,0.0,False
100,28,2,11,0,15,11,7,17,31,18,...,2,0,3,0.20,1.00,5.0,1.67,0.11,0.0,False

In [184]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   total_loc                         101 non-null    int64
 1   blank_loc                         101 non-null    int64
 2   comment_loc                       101 non-null    int64
 3   code_and_comment_loc              101 non-null    int64
 4   executable_loc                    101 non-null    int64
 5   unique_operands                   101 non-null    int64
 6   unique_operators                  101 non-null    int64
 7   total_operands                    101 non-null    int64
 8   total_operators                   101 non-null    int64
 9   halstead_vocabulary               101 non-null    int64
 10  halstead_length                   101 non-null    float64
 11  halstead_volume                   101 non-null    float64
 12  halstead_level                    101 non-null    float64
 13  halstead_difficulty               101 non-null    float64
 14  halstead_effort                   101 non-null    float64
 15  halstead_error                    101 non-null    float64
 16  halstead_time                     101 non-null    float64
 17  branch_count                      101 non-null    float64
 18  decision_count                    101 non-null    int64
 19  call_pairs                        101 non-null    int64
 20  condition_count                   101 non-null    int64
 21  multiple_condition_count          101 non-null    int64
 22  cyclomatic_complexity             101 non-null    int64
 23  cyclomatic_density                101 non-null    float64
 24  decision_density                  101 non-null    float64
 25  design_complexity                 101 non-null    float64
 26  design_density                    101 non-null    float64
 27  normalized_cyclomatic_complexity  101 non-null    float64
 28  formal_parameters                 101 non-null    float64
 29  defects                           101 non-null    bool
dtypes: bool(1), float64(14), int64(15)
memory usage: 23.1 KB

In [185]:
X = df.drop(columns=["defects"])
y = df["defects"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["defects"] = y
df_scaled

,total_loc,blank_loc,comment_loc,code_and_comment_loc,executable_loc,unique_operands,unique_operators,total_operands,total_operators,halstead_vocabulary,...,condition_count,multiple_condition_count,cyclomatic_complexity,cyclomatic_density,decision_density,design_complexity,design_density,normalized_cyclomatic_complexity,formal_parameters,defects
0,-0.635395,-0.169398,-0.174880,-0.194953,-0.738813,-0.507931,-0.587433,-0.632041,-0.734367,-0.523506,...,-0.649652,-0.530071,-0.765021,-0.153369,-0.980810,-0.720988,-0.601754,-0.852566,-0.571266,False
1,-0.382738,-0.169398,-0.639694,-0.194953,-0.213782,-0.324056,-0.132791,-0.149431,-0.330636,-0.286136,...,-0.649652,-0.530071,-0.495797,-0.215238,-0.980810,-0.720988,-0.601754,-0.598182,-0.571266,False
2,-0.029018,-0.169398,1.064623,-0.194953,-0.476297,0.043693,0.776492,-0.149431,-0.099933,0.188603,...,-0.054955,-0.530071,0.042649,0.039969,0.479632,-0.720988,-0.601754,0.037780,-0.571266,False
3,0.981611,-0.169398,1.839312,-0.194953,0.508137,0.595316,2.140416,1.737136,1.514989,0.900712,...,1.530902,0.585287,1.927212,0.024502,0.611072,-0.429137,-0.538106,1.055319,-0.571266,False
4,-0.635395,-0.169398,-0.329818,-0.194953,-0.673184,-0.599868,1.003812,-0.500420,-0.474826,-0.167451,...,-0.451420,-0.530071,-0.226574,0.117305,1.940075,-0.720988,-0.601754,2.327242,1.612605,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.324702,-0.169398,0.754747,-0.194953,0.114363,0.135630,0.094529,0.508674,0.303797,0.069918,...,0.143277,0.027608,0.042649,-0.161103,0.479632,0.738268,0.282252,-0.598182,-0.571266,False
97,-0.584864,-0.169398,-0.794632,-0.194953,-0.410668,-0.599868,-1.269395,-0.719788,-0.647853,-0.760875,...,-0.649652,-0.530071,-0.765021,-0.261639,-0.980810,1.030119,3.641473,-1.106951,-0.571266,False
98,-0.534332,-0.169398,0.289933,-0.194953,-0.804442,-0.599868,-1.269395,-0.763662,-0.647853,-0.760875,...,-0.649652,-0.530071,-0.765021,-0.091501,-0.980810,1.030119,3.641473,-1.234143,-0.571266,False
99,1.537457,0.144532,1.839312,-0.194953,1.098798,1.146940,0.094529,0.859663,0.909393,0.722685,...,0.539741,-0.530071,0.850319,-0.176570,0.479632,1.613822,0.204459,-0.725374,-0.571266,False
100,0.375233,0.144532,0.909685,-0.194953,-0.016895,-0.232119,-0.360112,-0.324926,-0.186447,-0.286136,...,-0.253188,-0.530071,-0.226574,-0.192037,0.479632,0.738268,0.579277,-1.106951,-0.571266,False

In [187]:
df_scaled = df_scaled.rename(columns={"defects": "target"})
df_scaled["target"].value_counts()

target
False    86
True     15
Name: count, dtype: int64

In [188]:
df_scaled["target"] = (df_scaled["target"]).astype(int)
df_scaled["target"].value_counts()

target
0    86
1    15
Name: count, dtype: int64

# 20

In [189]:
df = pd.read_csv("../class_imbalance/dataset_949_arsenic-female-bladder.csv")
df

     group   conc   age    at.risk binaryClass
0        1    0.0  22.5  2595529.0           P
1        1    0.0  27.5  1846189.0           N
2        1    0.0  32.5  1402764.0           P
3        1    0.0  37.5  1215899.0           N
4        1    0.0  42.5  1191615.0           N
..     ...    ...   ...        ...         ...
554     43  934.0  62.5      401.0           N
555     43  934.0  67.5      236.0           N
556     43  934.0  72.5      126.0           N
557     43  934.0  77.5       70.0           P
558     43  934.0  82.5       59.0           P

[559 rows x 5 columns]

In [190]:
X = df.drop(columns=["binaryClass"])
y = df["binaryClass"]

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

df_scaled = X_scaled.copy()
df_scaled["binaryClass"] = y
df_scaled

        group      conc       age    at.risk binaryClass
0   -1.692228 -1.203645 -1.603567  14.227112           P
1   -1.692228 -1.203645 -1.336306  10.082273           N
2   -1.692228 -1.203645 -1.069045   7.629548           P
3   -1.692228 -1.203645 -0.801784   6.595938           N
4   -1.692228 -1.203645 -0.534522   6.461615           N
..        ...       ...       ...        ...         ...
554  1.692228  2.395283  0.534522  -0.127370           N
555  1.692228  2.395283  0.801784  -0.128282           N
556  1.692228  2.395283  1.069045  -0.128891           N
557  1.692228  2.395283  1.336306  -0.129200           P
558  1.692228  2.395283  1.603567  -0.129261           P

[559 rows x 5 columns]

In [191]:
df_scaled = df_scaled.rename(columns={"binaryClass": "target"})
df_scaled["target"].value_counts()

target
P    479
N     80
Name: count, dtype: int64

In [192]:
df_scaled["target"] = (df_scaled["target"] == "N").astype(int)
df_scaled["target"].value_counts()

target
0    479
1     80
Name: count, dtype: int64